# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_control_spec.device_control_pb2 as device__control__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in device_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceControlStub(object):
    """BROWSETERM_CLOUD_CONTROL_PLANE_MIGRATION.md Part 5: the Device Agent's single outbound
    bidirectional gRPC stream to Cloud over TLS/HTTP2/port 443. Device Agent always dials; Cloud
    never calls into a customer-controlled machine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/browseterm.device.control.v1.DeviceControl/Connect',
                request_serializer=device__control__pb2.DeviceToCloud.SerializeToString,
                response_deserializer=device__control__pb2.CloudToDevice.FromString,
                _registered_method=True)


class DeviceControlServicer(object):
    """BROWSETERM_CLOUD_CONTROL_PLANE_MIGRATION.md Part 5: the Device Agent's single outbound
    bidirectional gRPC stream to Cloud over TLS/HTTP2/port 443. Device Agent always dials; Cloud
    never calls into a customer-controlled machine.
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=device__control__pb2.DeviceToCloud.FromString,
                    response_serializer=device__control__pb2.CloudToDevice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browseterm.device.control.v1.DeviceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browseterm.device.control.v1.DeviceControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceControl(object):
    """BROWSETERM_CLOUD_CONTROL_PLANE_MIGRATION.md Part 5: the Device Agent's single outbound
    bidirectional gRPC stream to Cloud over TLS/HTTP2/port 443. Device Agent always dials; Cloud
    never calls into a customer-controlled machine.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/browseterm.device.control.v1.DeviceControl/Connect',
            device__control__pb2.DeviceToCloud.SerializeToString,
            device__control__pb2.CloudToDevice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
