# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_control_spec.local_device_agent_pb2 as local__device__agent__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in local_device_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocalDeviceAgentStub(object):
    """Migration Part 12: Device Agent's private, ClusterIP-only local API for Status Monitor, Reaper,
    Snapshot Job and Socket-SSH - replaces every local job's direct use of the global
    CLOUD_INTERNAL_API_TOKEN against Cloud. Device Agent forwards what needs to reach Cloud over
    its own already-authenticated control stream (Part 6); local callers never hold a Cloud
    credential of any kind, only network access to this ClusterIP service (gated further by
    NetworkPolicy, not authentication - see Part 12's own doc section on this).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportContainerStatus = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportContainerStatus',
                request_serializer=local__device__agent__pb2.StatusReport.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportSnapshotProgress = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportSnapshotProgress',
                request_serializer=local__device__agent__pb2.SnapshotProgress.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestHibernate = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/RequestHibernate',
                request_serializer=local__device__agent__pb2.HibernateRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.CommandReference.FromString,
                _registered_method=True)
        self.ConsumeTerminalTicket = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ConsumeTerminalTicket',
                request_serializer=local__device__agent__pb2.TerminalTicketRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.TerminalTarget.FromString,
                _registered_method=True)
        self.ReportTunnel = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportTunnel',
                request_serializer=local__device__agent__pb2.TunnelReport.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.GetTunnelGeneration = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/GetTunnelGeneration',
                request_serializer=local__device__agent__pb2.GetTunnelGenerationRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.GetTunnelGenerationResponse.FromString,
                _registered_method=True)
        self.GetActiveContainerIds = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/GetActiveContainerIds',
                request_serializer=local__device__agent__pb2.Empty.SerializeToString,
                response_deserializer=local__device__agent__pb2.ContainerIdList.FromString,
                _registered_method=True)
        self.ReconcileDeviceResources = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReconcileDeviceResources',
                request_serializer=local__device__agent__pb2.ReconcileResourcesRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.GetIdleContainers = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/GetIdleContainers',
                request_serializer=local__device__agent__pb2.GetIdleContainersRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.ContainerIdList.FromString,
                _registered_method=True)
        self.AllocateSnapshot = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/AllocateSnapshot',
                request_serializer=local__device__agent__pb2.AllocateSnapshotRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.SnapshotAllocation.FromString,
                _registered_method=True)
        self.ReportSnapshotResult = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportSnapshotResult',
                request_serializer=local__device__agent__pb2.SnapshotResultReport.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.GetContainer = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/GetContainer',
                request_serializer=local__device__agent__pb2.GetContainerRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.GetContainerResponse.FromString,
                _registered_method=True)
        self.UpdateContainerKubernetesId = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/UpdateContainerKubernetesId',
                request_serializer=local__device__agent__pb2.UpdateKubernetesIdRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)


class LocalDeviceAgentServicer(object):
    """Migration Part 12: Device Agent's private, ClusterIP-only local API for Status Monitor, Reaper,
    Snapshot Job and Socket-SSH - replaces every local job's direct use of the global
    CLOUD_INTERNAL_API_TOKEN against Cloud. Device Agent forwards what needs to reach Cloud over
    its own already-authenticated control stream (Part 6); local callers never hold a Cloud
    credential of any kind, only network access to this ClusterIP service (gated further by
    NetworkPolicy, not authentication - see Part 12's own doc section on this).
    """

    def ReportContainerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSnapshotProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHibernate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeTerminalTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTunnel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTunnelGeneration(self, request, context):
        """Tunnel Registrar's resync check (added 2026-09-30): ReportTunnel is fire-and-forget with no
        rejection signal, so a registrar whose locally-persisted generation counter ever falls behind
        Cloud's own (e.g. its PersistentVolumeClaim is lost/recreated, or a manual reset undershoots)
        would otherwise retry a permanently-too-low generation forever, silently dropped server-side.
        This is a synchronous, device-scoped read of Cloud's own authoritative value - see
        GetTunnelGenerationResponse's own comment for how a caller is expected to use it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveContainerIds(self, request, context):
        """The 6 RPCs below finish Part 12: the last local-stack call sites that still used the global
        CLOUD_INTERNAL_API_TOKEN secret (status_monitor's resource-drift reconciler, reaper's idle
        sweep, snapshot_job's allocate/report, and container-maker's one remaining direct DB-row
        lookup) now go through Device Agent's own per-device Bearer credential instead, like every
        other local caller already does. All six need a real response back (not just an Ack a caller
        ignores), so - same reasoning as RequestHibernate/ConsumeTerminalTicket/GetTunnelGeneration
        above - they go through Device Agent's synchronous cloud_client HTTP path, not the
        fire-and-forget control stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileDeviceResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdleContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSnapshotResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContainerKubernetesId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalDeviceAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportContainerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportContainerStatus,
                    request_deserializer=local__device__agent__pb2.StatusReport.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'ReportSnapshotProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSnapshotProgress,
                    request_deserializer=local__device__agent__pb2.SnapshotProgress.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'RequestHibernate': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHibernate,
                    request_deserializer=local__device__agent__pb2.HibernateRequest.FromString,
                    response_serializer=local__device__agent__pb2.CommandReference.SerializeToString,
            ),
            'ConsumeTerminalTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeTerminalTicket,
                    request_deserializer=local__device__agent__pb2.TerminalTicketRequest.FromString,
                    response_serializer=local__device__agent__pb2.TerminalTarget.SerializeToString,
            ),
            'ReportTunnel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTunnel,
                    request_deserializer=local__device__agent__pb2.TunnelReport.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'GetTunnelGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTunnelGeneration,
                    request_deserializer=local__device__agent__pb2.GetTunnelGenerationRequest.FromString,
                    response_serializer=local__device__agent__pb2.GetTunnelGenerationResponse.SerializeToString,
            ),
            'GetActiveContainerIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveContainerIds,
                    request_deserializer=local__device__agent__pb2.Empty.FromString,
                    response_serializer=local__device__agent__pb2.ContainerIdList.SerializeToString,
            ),
            'ReconcileDeviceResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileDeviceResources,
                    request_deserializer=local__device__agent__pb2.ReconcileResourcesRequest.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'GetIdleContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdleContainers,
                    request_deserializer=local__device__agent__pb2.GetIdleContainersRequest.FromString,
                    response_serializer=local__device__agent__pb2.ContainerIdList.SerializeToString,
            ),
            'AllocateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateSnapshot,
                    request_deserializer=local__device__agent__pb2.AllocateSnapshotRequest.FromString,
                    response_serializer=local__device__agent__pb2.SnapshotAllocation.SerializeToString,
            ),
            'ReportSnapshotResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSnapshotResult,
                    request_deserializer=local__device__agent__pb2.SnapshotResultReport.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'GetContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainer,
                    request_deserializer=local__device__agent__pb2.GetContainerRequest.FromString,
                    response_serializer=local__device__agent__pb2.GetContainerResponse.SerializeToString,
            ),
            'UpdateContainerKubernetesId': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContainerKubernetesId,
                    request_deserializer=local__device__agent__pb2.UpdateKubernetesIdRequest.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browseterm.device.control.v1.LocalDeviceAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browseterm.device.control.v1.LocalDeviceAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalDeviceAgent(object):
    """Migration Part 12: Device Agent's private, ClusterIP-only local API for Status Monitor, Reaper,
    Snapshot Job and Socket-SSH - replaces every local job's direct use of the global
    CLOUD_INTERNAL_API_TOKEN against Cloud. Device Agent forwards what needs to reach Cloud over
    its own already-authenticated control stream (Part 6); local callers never hold a Cloud
    credential of any kind, only network access to this ClusterIP service (gated further by
    NetworkPolicy, not authentication - see Part 12's own doc section on this).
    """

    @staticmethod
    def ReportContainerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportContainerStatus',
            local__device__agent__pb2.StatusReport.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSnapshotProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportSnapshotProgress',
            local__device__agent__pb2.SnapshotProgress.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHibernate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/RequestHibernate',
            local__device__agent__pb2.HibernateRequest.SerializeToString,
            local__device__agent__pb2.CommandReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeTerminalTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ConsumeTerminalTicket',
            local__device__agent__pb2.TerminalTicketRequest.SerializeToString,
            local__device__agent__pb2.TerminalTarget.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTunnel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportTunnel',
            local__device__agent__pb2.TunnelReport.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTunnelGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/GetTunnelGeneration',
            local__device__agent__pb2.GetTunnelGenerationRequest.SerializeToString,
            local__device__agent__pb2.GetTunnelGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveContainerIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/GetActiveContainerIds',
            local__device__agent__pb2.Empty.SerializeToString,
            local__device__agent__pb2.ContainerIdList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileDeviceResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReconcileDeviceResources',
            local__device__agent__pb2.ReconcileResourcesRequest.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdleContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/GetIdleContainers',
            local__device__agent__pb2.GetIdleContainersRequest.SerializeToString,
            local__device__agent__pb2.ContainerIdList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/AllocateSnapshot',
            local__device__agent__pb2.AllocateSnapshotRequest.SerializeToString,
            local__device__agent__pb2.SnapshotAllocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSnapshotResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportSnapshotResult',
            local__device__agent__pb2.SnapshotResultReport.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/GetContainer',
            local__device__agent__pb2.GetContainerRequest.SerializeToString,
            local__device__agent__pb2.GetContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContainerKubernetesId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/UpdateContainerKubernetesId',
            local__device__agent__pb2.UpdateKubernetesIdRequest.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
