# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_control_spec.local_device_agent_pb2 as local__device__agent__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in local_device_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocalDeviceAgentStub(object):
    """Migration Part 12: Device Agent's private, ClusterIP-only local API for Status Monitor, Reaper,
    Snapshot Job and Socket-SSH - replaces every local job's direct use of the global
    CLOUD_INTERNAL_API_TOKEN against Cloud. Device Agent forwards what needs to reach Cloud over
    its own already-authenticated control stream (Part 6); local callers never hold a Cloud
    credential of any kind, only network access to this ClusterIP service (gated further by
    NetworkPolicy, not authentication - see Part 12's own doc section on this).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportContainerStatus = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportContainerStatus',
                request_serializer=local__device__agent__pb2.StatusReport.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportSnapshotProgress = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportSnapshotProgress',
                request_serializer=local__device__agent__pb2.SnapshotProgress.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestHibernate = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/RequestHibernate',
                request_serializer=local__device__agent__pb2.HibernateRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.CommandReference.FromString,
                _registered_method=True)
        self.ConsumeTerminalTicket = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ConsumeTerminalTicket',
                request_serializer=local__device__agent__pb2.TerminalTicketRequest.SerializeToString,
                response_deserializer=local__device__agent__pb2.TerminalTarget.FromString,
                _registered_method=True)
        self.ReportTunnel = channel.unary_unary(
                '/browseterm.device.control.v1.LocalDeviceAgent/ReportTunnel',
                request_serializer=local__device__agent__pb2.TunnelReport.SerializeToString,
                response_deserializer=local__device__agent__pb2.Ack.FromString,
                _registered_method=True)


class LocalDeviceAgentServicer(object):
    """Migration Part 12: Device Agent's private, ClusterIP-only local API for Status Monitor, Reaper,
    Snapshot Job and Socket-SSH - replaces every local job's direct use of the global
    CLOUD_INTERNAL_API_TOKEN against Cloud. Device Agent forwards what needs to reach Cloud over
    its own already-authenticated control stream (Part 6); local callers never hold a Cloud
    credential of any kind, only network access to this ClusterIP service (gated further by
    NetworkPolicy, not authentication - see Part 12's own doc section on this).
    """

    def ReportContainerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSnapshotProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHibernate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeTerminalTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTunnel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalDeviceAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportContainerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportContainerStatus,
                    request_deserializer=local__device__agent__pb2.StatusReport.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'ReportSnapshotProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSnapshotProgress,
                    request_deserializer=local__device__agent__pb2.SnapshotProgress.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
            'RequestHibernate': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHibernate,
                    request_deserializer=local__device__agent__pb2.HibernateRequest.FromString,
                    response_serializer=local__device__agent__pb2.CommandReference.SerializeToString,
            ),
            'ConsumeTerminalTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeTerminalTicket,
                    request_deserializer=local__device__agent__pb2.TerminalTicketRequest.FromString,
                    response_serializer=local__device__agent__pb2.TerminalTarget.SerializeToString,
            ),
            'ReportTunnel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTunnel,
                    request_deserializer=local__device__agent__pb2.TunnelReport.FromString,
                    response_serializer=local__device__agent__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browseterm.device.control.v1.LocalDeviceAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browseterm.device.control.v1.LocalDeviceAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalDeviceAgent(object):
    """Migration Part 12: Device Agent's private, ClusterIP-only local API for Status Monitor, Reaper,
    Snapshot Job and Socket-SSH - replaces every local job's direct use of the global
    CLOUD_INTERNAL_API_TOKEN against Cloud. Device Agent forwards what needs to reach Cloud over
    its own already-authenticated control stream (Part 6); local callers never hold a Cloud
    credential of any kind, only network access to this ClusterIP service (gated further by
    NetworkPolicy, not authentication - see Part 12's own doc section on this).
    """

    @staticmethod
    def ReportContainerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportContainerStatus',
            local__device__agent__pb2.StatusReport.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSnapshotProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportSnapshotProgress',
            local__device__agent__pb2.SnapshotProgress.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHibernate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/RequestHibernate',
            local__device__agent__pb2.HibernateRequest.SerializeToString,
            local__device__agent__pb2.CommandReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeTerminalTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ConsumeTerminalTicket',
            local__device__agent__pb2.TerminalTicketRequest.SerializeToString,
            local__device__agent__pb2.TerminalTarget.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTunnel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browseterm.device.control.v1.LocalDeviceAgent/ReportTunnel',
            local__device__agent__pb2.TunnelReport.SerializeToString,
            local__device__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
